import os
import time 
from termcolor import colored, cprint
time.sleep(0.0)
os.system('pip install random')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install string-color')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install string')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install pyfiglet')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install instaloader')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install phonenumbers')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install wikipedia')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install threading')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install foundation-platform')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install platform')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install psutil')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install GPUtil')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install tabulate')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install playsound2')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install playsound')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install pycopy-urllib.request')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install urllib.request')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install colored')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install subprocess')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install pynput')
print(colored("######## DONE ########",'green'))
time.sleep(0.0)
os.system('pip install subprocess32')
print(colored("######## start clear .... [10s] ########",'green'))
time.sleep(10)
os.system('clear')
